version: '3.8'

services:
    postgresql:
        container_name: postgres
        image: postgres:11.12
        restart: unless-stopped
        environment:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demopw
          POSTGRES_DB: delivery
          PGDATA: /var/lib/postgresql/data/pgdata
        ports:
          - 5432:5432
        volumes:
          - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    spring:
        build: ./projService
        container_name: delivery-service
        restart: unless-stopped
        image: delivery-service
        ports:
            - 8080:8080
        depends_on: 
            - postgresql