version: '3.8'

services:
    db-generic:
        container_name: postgres-generic
        image: postgres:11.12
        restart: unless-stopped
        environment:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demopw
          POSTGRES_DB: delivery
          PGDATA: /var/lib/postgresql/data/pgdata
        ports:
          - 5432:5432
        volumes:
          - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    


    db-specific:
        container_name: postgres-specific
        image: postgres:11.12
        restart: unless-stopped
        environment:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demopw
          POSTGRES_DB: shop
          PGDATA: /var/lib/postgresql/data/pgdata
        ports:
          - 5433:5433
        volumes:
          - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    

    # specific:
    #     build: ./projSpecificService
    #     container_name: delivery-service
    #     restart: unless-stopped
    #     image: specific-service
    #     ports:
    #         - 8080:8080
    #     depends_on: 
    #         - db-specific


    # generic:
    #     build: /projGenericService
    #     container_name: generic-service
    #     restart: unless-stopped
    #     image: generic-service
    #     ports:
    #         - 8000:8000
    #     depends_on: 
    #         - db-generic
