name: CD to Google Computer Engine VM

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_SSH_HOST }}
          user: ${{ secrets.DOCKER_SSH_USERNAME }}
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          command: |
            cd tqs-delivery
            git pull
            export API_URL=35.246.29.122
            docker container stop $(docker container ls -aq)
            docker container rm $(docker container ls -aq)
            docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD:$PWD" \
            -e API_URL=${API_URL} \
            -w="$PWD" \
            docker/compose:1.29.2 build
            docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD:$PWD" \
            -w="$PWD" \
            docker/compose:1.29.2 up -d
            
