name: CD to Google Computer Engine VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Deploy to Docker Host
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: tqs@35.246.29.122
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        args: up -d
        pre_deployment_command_args: 'cd tqs-delivery && git pull && export API_URL=35.246.29.122'
        docker_prune: 'true'
        pull_images_first: 'true'
