name: CD to Google Computer Engine VM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DOCKER_SSH_HOST }}
          username: ${{ secrets.DOCKER_SSH_USERNAME }}
          key: ${{ DOCKER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DOCKER_SSH_PORT }}
          script: |
            cd tqs-delivery
            git pull
            export API_URL=35.246.29.122
            yes | docker system prune -a
            docker-compose up -d
