name: Spring Boot CI Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Running Verify Lifecycle
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Verify code executing each default lifecycle phase and IT tests
      run: mvn -B clean verify
      working-directory: ./projGenericService

    - name: Verify code executing each default lifecycle phase and IT tests
      run: mvn -B clean verify
      working-directory: ./projSpecificService
